services:
  btc-trading-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: btc-trading-bot
    restart: unless-stopped
    network_mode: "bridge"
    ports:
      - "8080:8080"
    volumes:
      # 挂载.env文件（必需）
      - ./.env:/app/.env:ro
      # 持久化数据（可选）
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
    dns:
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # 健康检查（使用Python而不是curl）
    healthcheck:
      test: [ "CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/api/dashboard', timeout=5)" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
